# Generated by Django 5.2.1 on 2025-05-27 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Dieta')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, help_text='Deixe em branco se a dieta não tiver um prazo definido.', null=True, verbose_name='Data de Fim')),
                ('nutritionist_name', models.CharField(blank=True, max_length=150, verbose_name='Nutricionista/Clínica')),
                ('goal', models.TextField(blank=True, help_text='Ex: Perda de peso, ganho de massa, reeducação alimentar.', verbose_name='Objetivo')),
                ('attachment', models.FileField(blank=True, help_text='Anexe o arquivo PDF ou imagem original da dieta.', null=True, upload_to='diets/', verbose_name='Anexo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Plano Alimentar',
                'verbose_name_plural': 'Planos Alimentares',
                'ordering': ['-start_date', 'user'],
            },
        ),
    ]
