# Generated by Django 5.2.1 on 2025-05-27 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Diet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Componente')),
                ('component_type', models.CharField(choices=[('PROTEIN', 'Proteína'), ('CARBOHYDRATE', 'Carboidrato'), ('VEGETABLE', 'Vegetal/Legume'), ('SAUCE', 'Molho'), ('OTHER', 'Outro')], max_length=20, verbose_name='Tipo de Componente')),
                ('description', models.TextField(blank=True, verbose_name='Modo de Preparo/Descrição')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='components/', verbose_name='Foto')),
                ('calories_per_serving', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calorias por porção')),
            ],
            options={
                'verbose_name': 'Componente da Refeição',
                'verbose_name_plural': 'Componentes da Refeição',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Ex: 1.5kg de bife de patinho, 2 cebolas grandes', max_length=255, verbose_name='Descrição do Ingrediente')),
                ('meal_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='MealPrep.mealcomponent', verbose_name='Componente da Refeição')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
        migrations.CreateModel(
            name='MealPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Marmita')),
                ('target_date', models.DateField(help_text='Data para a qual a marmita está planejada. Usada para agrupar por semana ou mês.', verbose_name='Data Planejada')),
                ('meal_type', models.CharField(choices=[('LUNCH', 'Almoço'), ('DINNER', 'Janta')], max_length=10, verbose_name='Tipo de Refeição')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade a Fazer')),
                ('is_prepared', models.BooleanField(default=False, verbose_name='Já foi feita?')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('prepared_on', models.DateField(blank=True, null=True, verbose_name='Data da Preparação')),
                ('diet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_preps', to='Diet.diet', verbose_name='Plano Alimentar')),
                ('intended_for', models.ManyToManyField(help_text='Selecione para quem são estas marmitas.', related_name='meal_preps', to=settings.AUTH_USER_MODEL, verbose_name='Destinado para')),
            ],
            options={
                'verbose_name': 'Marmita Planejada',
                'verbose_name_plural': 'Marmitas Planejadas',
                'ordering': ['-target_date'],
            },
        ),
        migrations.CreateModel(
            name='MealPrepComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Quantidade')),
                ('unit_of_measure', models.CharField(choices=[('g', 'Gramas'), ('ml', 'Mililitros'), ('un', 'Unidade(s)'), ('colher', 'Colher(es)')], default='g', max_length=10, verbose_name='Unidade de Medida')),
                ('notes', models.CharField(blank=True, help_text='Ex: um pouco mais apimentado, sem sal, etc.', max_length=255, verbose_name='Observações')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealPrep.mealcomponent')),
                ('meal_prep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MealPrep.mealprep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Componente da Marmita',
                'verbose_name_plural': 'Componentes das Marmitas',
                'unique_together': {('meal_prep', 'component', 'user')},
            },
        ),
        migrations.AddField(
            model_name='mealprep',
            name='components',
            field=models.ManyToManyField(through='MealPrep.MealPrepComponent', to='MealPrep.mealcomponent', verbose_name='Componentes'),
        ),
    ]
